
# Hide a warning in lwIP
set_source_files_properties(
  "${PICO_LWIP_PATH}/src/apps/altcp_tls/altcp_tls_mbedtls.c"
  PROPERTIES COMPILE_OPTIONS "-Wno-unused-result"
)

# Get the Nim include path to get nimbase.h
execute_process(
  COMMAND nim dump --dump.format:json --hints:off -
  OUTPUT_VARIABLE NIM_DUMP_JSON
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
string(JSON NIM_LIB_DIR GET "${NIM_DUMP_JSON}" libpath)

file(TO_CMAKE_PATH "${PICO_SDK_PATH}" CMAKE_PICO_SDK_PATH)
file(CONFIGURE
  OUTPUT ${CMAKE_BINARY_DIR}/generated/cmakecache.nim
  CONTENT "# autogenerated by picostdlib.cmake
const PICO_SDK_PATH* = r\"${CMAKE_PICO_SDK_PATH}\"
const PICO_BOARD* = r\"${PICO_BOARD}\"
const CMAKE_BUILD_TYPE* = r\"${CMAKE_BUILD_TYPE}\"
const PICO_CYW43_SUPPORTED* = r\"${PICO_CYW43_SUPPORTED}\" == \"1\"
const PICO_MBEDTLS_PATH* = r\"${PICO_MBEDTLS_PATH}\"
const PICO_LWIP_PATH* = r\"${PICO_LWIP_PATH}\"
const FREERTOS_KERNEL_PATH* = r\"${FREERTOS_KERNEL_PATH}\"\n"
)

function(picostdlib_target target name)
  set(NIMCACHE_DIR "${CMAKE_BINARY_DIR}/${target}/nimcache")
  set(NIMCACHE_JSON_FILE "${NIMCACHE_DIR}/${name}.json")

  if(NOT EXISTS ${NIMCACHE_JSON_FILE})
    file(CONFIGURE OUTPUT ${NIMCACHE_JSON_FILE} CONTENT "")
  endif()

  set(NIM_SOURCES "")
  set(NIMCACHE_JSON_DATA "")

  # Read the nimcache JSON file to get the source files
  if(EXISTS ${NIMCACHE_JSON_FILE})
    file(READ "${NIMCACHE_JSON_FILE}" NIMCACHE_JSON_DATA)
  endif()

  if(NIMCACHE_JSON_DATA)
    string(JSON cfilelength LENGTH "${NIMCACHE_JSON_DATA}" compile)
    math(EXPR cfilelength "${cfilelength} - 1")
    foreach(IDX RANGE ${cfilelength})
        string(JSON CUR_FILE GET "${NIMCACHE_JSON_DATA}" compile ${IDX} 0)
        string(REPLACE "\\" "/" CUR_FILE "${CUR_FILE}")
        list(APPEND NIM_SOURCES ${CUR_FILE})
    endforeach()
    # Suppress gcc warnings for nim-generated files
    set_source_files_properties(${NIM_SOURCES} PROPERTIES COMPILE_OPTIONS "-w")
    target_sources(${target} PRIVATE ${NIM_SOURCES})
  endif()

  target_include_directories(${target} PRIVATE ${NIM_LIB_DIR})

  set(PICOSTDLIB_IMPORTS_PATH "${CMAKE_BINARY_DIR}/${target}/imports.cmake")
  if(NOT EXISTS ${PICOSTDLIB_IMPORTS_PATH})
    file(CONFIGURE OUTPUT ${PICOSTDLIB_IMPORTS_PATH} CONTENT "# generated by cmake")
  endif()

  target_link_libraries(${target} hardware_claim) # fallback to something

  include(${PICOSTDLIB_IMPORTS_PATH}) # Include our generated file

  # recompile when nim build changes
  set_property(
    DIRECTORY
    APPEND
    PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${NIMCACHE_JSON_FILE}"
    "${PICOSTDLIB_IMPORTS_PATH}"
  )
endfunction()
